#!/bin/bash
set -e  # Exit if any command fails
set -x
set -o pipefail

echo "Setting up archive-exercise..."
chmod +x /usr/bin/archive-exercise
echo "Setting up GROUP_ARCHIVING_PATH env variable to default /tmp. Adapt as required to determine storage path."
export GROUP_ARCHIVING_PATH=/tmp
echo "Installation complete!"